INSERT INTO core.dim_item (
    source_item_code,
    item_name,
    generic_name,
    item_type,
    item_group,
    item_category,
    abc_class,
    ven_class,
    standard_unit,
    strength_text,
    dosage_form,
    manufacturer_name,
    is_active,
    is_drug,
    is_supply,
    first_seen_ts,
    last_seen_ts,
    current_record_flag
)
SELECT
    s.source_item_code,
    s.item_name,
    s.generic_name,
    s.item_type,
    s.item_group,
    s.item_category,
    s.abc_class,
    s.ven_class,
    s.standard_unit,
    s.strength_text,
    s.dosage_form,
    s.manufacturer_name,
    COALESCE(s.is_active, TRUE),
    CASE WHEN LOWER(COALESCE(s.item_type, '')) = 'drug' THEN TRUE ELSE FALSE END,
    CASE WHEN LOWER(COALESCE(s.item_type, '')) = 'supply' THEN TRUE ELSE FALSE END,
    NOW(),
    NOW(),
    TRUE
FROM stg.item_master s
WHERE s.etl_batch_id = :etl_batch_id
ON CONFLICT (source_item_code)
DO UPDATE SET
    item_name = EXCLUDED.item_name,
    generic_name = EXCLUDED.generic_name,
    item_type = EXCLUDED.item_type,
    item_group = EXCLUDED.item_group,
    item_category = EXCLUDED.item_category,
    abc_class = EXCLUDED.abc_class,
    ven_class = EXCLUDED.ven_class,
    standard_unit = EXCLUDED.standard_unit,
    strength_text = EXCLUDED.strength_text,
    dosage_form = EXCLUDED.dosage_form,
    manufacturer_name = EXCLUDED.manufacturer_name,
    is_active = EXCLUDED.is_active,
    is_drug = EXCLUDED.is_drug,
    is_supply = EXCLUDED.is_supply,
    last_seen_ts = NOW(),
    current_record_flag = TRUE;
